2023-11-05 15:47:23,958 - DEBUG - This is a debug message
2023-11-05 15:47:23,958 - INFO - This is an info message
2023-11-05 15:47:23,959 - WARNING - This is a warning message
2023-11-05 15:47:23,959 - ERROR - This is an error message
2023-11-05 15:47:23,959 - CRITICAL - This is a critical message
2023-11-05 15:49:02,226 - ERROR - Exception occurred
Traceback (most recent call last):
  File "c:\Users\user\python-advanced-course\logging_exceptions.py", line 7, in <module>
    result = 10 / 0
ZeroDivisionError: division by zero
11111111111111111111
